
import { useState, useCallback, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface UseInvitationCodeProps {
  classroomId: string;
}

export const useInvitationCode = ({ classroomId }: UseInvitationCodeProps) => {
  const [invitationCode, setInvitationCode] = useState('');
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  // Fetch existing invitation code on mount
  useEffect(() => {
    const fetchExistingCode = async () => {
      if (!classroomId) return;
      
      try {
        setLoading(true);
        console.log("[useInvitationCode] Fetching existing code for classroom:", classroomId);
        
        // Check if there's an existing invitation code for this classroom
        const { data, error } = await supabase
          .from('class_invitations')
          .select('invitation_token, expires_at')
          .eq('classroom_id', classroomId)
          .eq('status', 'pending')
          .eq('email', 'general_invitation@blockward.app')
          .order('created_at', { ascending: false })
          .limit(1);
          
        if (error) throw error;
        
        if (data && data.length > 0) {
          // Check if the invitation is still valid
          const expiresAt = new Date(data[0].expires_at);
          const now = new Date();
          
          if (expiresAt > now) {
            console.log("[useInvitationCode] Found existing valid invitation code:", data[0].invitation_token);
            setInvitationCode(data[0].invitation_token);
          } else {
            console.log("[useInvitationCode] Found expired invitation, generating new one");
            await generateInviteCode();
          }
        }
      } catch (err) {
        console.error("[useInvitationCode] Error fetching invitation code:", err);
      } finally {
        setLoading(false);
      }
    };
    
    fetchExistingCode();
  }, [classroomId]);

  // Generate a new invitation code using the database function
  const generateInviteCode = useCallback(async () => {
    setLoading(true);
    try {
      console.log("[useInvitationCode] Generating new invitation code for classroom:", classroomId);
      
      // Calculate expiration (90 days from now)
      const expiresAt = new Date();
      expiresAt.setDate(expiresAt.getDate() + 90);
      
      console.log("[useInvitationCode] Creating invitation with auto-generated token");
      
      // Store the invitation code in Supabase - let the database generate the code
      const { data: invitation, error: inviteError } = await supabase
        .from('class_invitations')
        .insert({
          classroom_id: classroomId,
          email: 'general_invitation@blockward.app', // Marker for general invitations
          status: 'pending',
          expires_at: expiresAt.toISOString()
          // invitation_token will be auto-generated by the database
        })
        .select()
        .single();
      
      if (inviteError) {
        throw new Error(inviteError.message || 'Failed to generate invitation code');
      }
      
      console.log("[useInvitationCode] Invitation created successfully:", invitation);
      setInvitationCode(invitation.invitation_token);
      
      toast({
        title: "Success",
        description: "New invitation code generated",
      });
      
      return invitation;
    } catch (error: any) {
      console.error("[useInvitationCode] Error generating invitation code:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to generate invitation code",
        variant: "destructive",
      });
      return null;
    } finally {
      setLoading(false);
    }
  }, [classroomId, toast]);

  // Function to get the full join URL
  const getJoinUrl = useCallback(() => {
    if (!invitationCode) return '';
    
    // Create a clean URL without "lovable" subdomain
    const currentHost = window.location.host;
    const cleanHost = currentHost.replace(/^lovable\./, '').replace(/^www\./, '');
    
    // Use blockward.app domain for production or the current cleaned domain for development
    const finalHost = process.env.NODE_ENV === 'production' ? 'blockward.app' : cleanHost;
    const protocol = window.location.protocol;
    
    // Generate the full URL with the invitation code
    return `${protocol}//${finalHost}/classes?code=${invitationCode}`;
  }, [invitationCode]);

  return {
    invitationCode,
    setInvitationCode,
    loading,
    generateInviteCode,
    getJoinUrl,
  };
};
